### PR TITLE
Fix track objects not updating their position on world origin shift

### LINKED ISSUE #441: Big Chunk System removes track objects
### Summary
Every time a big chunk change happens, the current loaded landscape gets moved to nowhere...
In the editor everything works fine. I only ca reproduce this ingame...

https://user-images.githubusercontent.com/39700889/205491444-a3a286b8-2e96-433a-b2a4-aa3d96572ec8.mp4

### PR DESCRIPTION
**Pull request by HaSa1002**
I guess the rails updated the TOs at some point which may have been removed by one of us because it is unbenefical coupling of classes.

Fixes #441

### CODE REVIEW

**Comment by DasCapschen** [comment]
No this should not be necessary. TrackObjects are inside the chunks, and iirc the whole chunk is shifted / the TrackObject parent node in the chunk is shifted.
It should not be necessary to shift every TrackObject individually (which is also very imperformant iirc)

**Comment by HaSa1002** [comment]
Sorry misclick

**Comment by HaSa1002** [comment]
> No this should not be necessary. TrackObjects are inside the chunks, and iirc the whole chunk is shifted / the TrackObject parent node in the chunk is shifted.

Nope we don't move the chunk. We move the buildings and the grass. The TO parent is not moved because you encountered some issue (?) I belive at some point the rails called the update of the rail attachements but that is no more.

https://github.com/Libre-TrainSim/Libre-TrainSim/blob/master/src/Data/Scripts/chunk.gd#L69-L81

> It should not be necessary to shift every TrackObject individually (which is also very imperformant iirc)

Well, I agree but it never worked that way.

**Comment by DasCapschen** [comment]
Oh, you are right, I remember now... Track Objects really need a refactor at some point I think 🙈

**Review by DasCapschen — APPROVED** [review]
lgtm

**Pull request merged**
