### PR TITLE
Fix message label readability using blur

### PR DESCRIPTION
**Pull request by HaSa1002**
This adds a simple blur shader and material to increase readability of the message label.

I also added the blur to the pause menu background.

### CODE REVIEW

**Comment by DasCapschen** [comment]
Screenshot? Before / After?

**Comment by HaSa1002** [comment]
Can give one sometime this week.

**Comment by HaSa1002** [comment]
Without:
grafik

With:
grafik

**Comment by DasCapschen** [comment]
That is awesome!

**Review by DasCapschen — APPROVED** [review]
lgtm

**Pull request merged**
