### PR TITLE
Version Exporter: Ignore MacOS Key Modifications

### PR DESCRIPTION
**Pull request by HaSa1002**
This will hopefully point out what I misconfigured for clean builds to happen...

### CODE REVIEW

**Comment by HaSa1002** [comment]
Oh wow... It's because of magic... (see https://github.com/godotengine/godot/issues/35355)

**Comment by HaSa1002** [comment]
I am thinking to add an explicit ignore for this change

**Comment by HaSa1002** [comment]
Ok it's now ignored. Not the nicest solution but it has to suffice as workaround until we upgraded to Godot 4.

**Comment by HaSa1002** [comment]
All downloads should now print the version number in white.

**Review by DasCapschen — COMMENTED** [review]
This is messed up 🙈 

Why do we even need this dirty vs clean thing again?

**Comment by HaSa1002** [comment]
Well while we don't need it technically, rejecting dirty builds is good practice (see game.ci for example) because it helps to catch changes with unwanted side effect.

**Review by DasCapschen — APPROVED** [review]
Well alright. It's hacky, but I guess it's okay 🙈

**Pull request merged**
