### PR TITLE
Add Debug UI (FPS Counter)

### LINKED ISSUE #340: Show FPS in-game
Would it be possible to have an option in Settings to turn on an FPS counter?

My laptop is struggling with the frame rate, and it would be nice to have an FPS counter while adjusting the graphics options.

### PR DESCRIPTION
**Pull request by DasCapschen**
Adds an FPS Counter in the upper right.
Fixes #340 

Can be activated by pressing `F12` at any time. (uses a keybinding, so can be rebound later)

grafik

### CODE REVIEW

**Review by HaSa1002 — CHANGES_REQUESTED** [review]
FYI, file names in Godot should be lower_case style.
Please prefer  `_unhandled_input` over `_input` whenever possible.

**Comment by DasCapschen** [comment]
My files are in `lower_case` style ... ❓ 

I think this situation calls for _input.
Its a debug interface, you don't want anything else blocking it from opening.

**Comment by HaSa1002** [comment]
> My files are in lower_case style ... ❓

My bad. I was referring to the `misc` folder but apperantly there is already one.

> I think this situation calls for _input.
Its a debug interface, you don't want anything else blocking it from opening.

I disagree because of the reasons I posted in our private conversation.

**Comment by DasCapschen** [comment]
Changed to `_unhandled_input` @HaSa1002

**Comment by HaSa1002** [comment]
Thanks. Please squash the last two commits together 😇

**Comment by DasCapschen** [comment]
Done. Though you could've just squash-merged 😛

**Review by HaSa1002 — APPROVED** [review]
lgtm. No, because first, I don't like squash merges and second, the movement of the logo files should be a seperate commit

**Comment by HaSa1002** [comment]
thanks ❤️

**Pull request merged**
