### PR TITLE
fix getPathFromTo

### LINKED ISSUE #203: getPathFromToHelper crash
Function `getPathFromToHelper` in Wagon.gd:
```gdscript
if connectionN.is_in_group("PassengerPathNode"):
```
"attempt to call is_in_group on null instance"

### PR DESCRIPTION
**Pull request by DasCapschen**
fixes #203

### CODE REVIEW

**Comment by HaSa1002** [comment]
IMO those connections should be NodePaths

**Comment by DasCapschen** [comment]
They cannot be NodePaths, because NodePath is always relative to the Node they are saved on, but the path needs to be relative to the Wagon...
Although, I think I can change the code to be relative to the current Node instead of the wagon :thinking:

**Comment by DasCapschen** [comment]
Okay, it is now using NodePaths.

BUT!
I just noticed it is actually still broken.
Passengers never sit down, they only get in the train and then get stuck on some path node.
I mean, it's better than before, where passengers got stuck outside the train, but yeah... :/

**Review by HaSa1002 — APPROVED** [review]
I suppose it is better than now. Let's merge it and fix more later :)

**Review by HaSa1002 — APPROVED** [review]
works fine

**Pull request merged**
