### PR TITLE
Added spanish translation.

### PR DESCRIPTION
**Pull request by mdtrooper**
Thanks is a awesome game. I think that the next version will be a good free software alternative to close source train simulators.

### CODE REVIEW

**Comment by HaSa1002** [comment]
Hey @mdtrooper,
welcome to Libre Train Sim as a contributer 🥳. Thank you very much for you PR. It is looking pretty good (albeit I don't speak Spanish so 🤷). I would like you to ask for two things:
1. Please either recommit with an email address provided on you GitHub account (tres.14159@gmail.com is public) or add the email address, you used to commit, to you GitHub account. Without the information GH won't be able to recognize you.
2. Please rebase your PR and combine the two versions into one.

If you any help, you can either ask me here or ask on Discord.

**Comment by mdtrooper** [comment]
Well, I did the commit with the computer of company (and the email was the company). Well now I do some dump changes for upload the commits with the same email of github. Is it ok?

**Comment by HaSa1002** [comment]
Oh well...
Let's see. Here are the cli commands, you can use to squash the commits and rebase the branch. For more background info, please visit this guide: https://docs.godotengine.org/en/stable/community/contributing/pr_workflow.html
Config of local copy:
```cmd
git stash | git fetch | git checkout spanish_translation | git pull | git remote add upstream https://github.com/Libre-TrainSim/Libre-TrainSim.git
```
Squash commits and start rebase:
```cmd
 git reset --soft HEAD~3 | git commit -m "Add spanish translation" | git push -f | git pull upstream master -r
```
Go ahead and fix the conflicts. I can provide more help if needed.
```cmd
git rebase --continue
```
Quit the editor
```cmd
git push -f
```

**Comment by mdtrooper** [comment]
Ohh don't worry, it is more easy start a new branch with these changes, and close this pull request.

The new pull request is https://github.com/Libre-TrainSim/Libre-TrainSim/pull/257 .

**Pull request closed without merging**
