### PR TITLE
fix broken systems and improve PZB simulation with brake curves

### LINKED ISSUE #410: SiFa not working
### Summary
The SiFa system doesn't appear to be online, no matter the setting. It only works in the SiFa tutorial.

### How to reproduce
1. Open a map, for example "Tutorials/Free Driving", in advanced mode.
2. Drive for a while.
3. Notice that the SiFa warning never appears.

### Observed behavior
The SiFa feature doesn't seem to be working. You can drive the train without ever needing to press 'Space'.

### Expected behavior
After 30 seconds of driving in advanced mode, the SiFa system applies emergency brakes. It also audibly warns you a few seconds before. Pressing 'Space' resets the timer.

### Version
 - Game Version: commit 25ed03acb353fe4ef882ddaa844d8fcb32c0c58a

### Additional information
I'm not sure when this broke. It worked way back in 0.8.
It's still working in the "German-Safety-Tutorials/SiFa" scenario.

### PR DESCRIPTION
**Pull request by DasCapschen**
fixes #410

### CODE REVIEW

**Review by nalquas — DISMISSED** [review]
lgtm

**Comment by nalquas** [comment]
Sorry, forgot to test before approving as the code looks good.

Trying to start a map throws the following error:
`Parser Error: The setter function isn't defined.` at `res://Data/Scripts/PZBModule.gd:45`

**Comment by DasCapschen** [comment]
Oops, sorry about that. Should work again now.

**Review by nalquas — APPROVED** [review]
Tested, works perfectly now.
lgtm

**Pull request merged**
