### PR TITLE
Remove content import feature

### LINKED ISSUE #313: Bug: Import of .pck files doesn't work
grafik

How to reproduce:

content -> Import -> Select a .pck file

### PR DESCRIPTION
**Pull request by HaSa1002**
Fixes #313

Feature is not supportable for 0.9

### CODE REVIEW

**Comment by Jean28518** [comment]
? How to install addons easily?

**Comment by DasCapschen** [comment]
You need both a .pck file with the addon, and a mod config (content.tres).
Simply copying the .pck file is not enough. If you want to make a "import content" feature, either you need to copy a whole folder, containing both, or you could distribute addons as .zip files, which this method must then unpack into a subfolder in addons/

```
addons/
|---- my_addon/
       |---- content.tres
       |---- mod.pck
```


Also the function `ContentLoader.update_config()` does not even exist.

**Comment by Jean28518** [comment]
Thanks. For v1.0 we should implement such a feature :)

**Review by Jean28518 — APPROVED** [review]

**Comment by HaSa1002** [comment]
There is no Zip feature in Godot. At least none that has a GDScript interface

**Pull request merged**
