### PR TITLE
Improve input map for controllers

### PR DESCRIPTION
**Pull request by Jomosoto**
This is the layout (on an Xbox-controller):

Shoulder buttons:
- R2: Accelerate +
- R1: Accelerate -
- L2: Brake +
- L1: Brake -

ABXY buttons:
- A: SiFa
- B: PZB Ack
- Y: PZB Free
- X: PZB Comm

D-Pad:
- Left: Left door
- Right: Right door
- Up: Close doors
- Down: Horn

Sticks:
- Left down: Front light
- Right down: Inside light

I also added this layout to the OpenBVE layout, because I couldn't a default controller layout (Is there any?)

### CODE REVIEW

**Comment by HaSa1002** [comment]
I think the layout is sensible for a soft launch. But I have to test it to be sure. So please hold on a little while longer.

**Comment by HaSa1002** [comment]
> 
    R2: Accelerate +
    R1: Accelerate -
    L2: Brake +
    L1: Brake -

This feels unnatural. I'd prefer LT to accelerate and RT to deccelerate. Esp. since breaking is not used in the easy mode.

I dunno It's not perfect yet and feel like there's a lot more work for a proper controller support but I think it's fine for 0.9 and proper support is a 0.10 topic.

**Review by HaSa1002 — CHANGES_REQUESTED** [review]
see comment above

**Comment by Jomosoto** [comment]
> This feels unnatural. I'd prefer LT to accelerate and RT to deccelerate

I swapped it. I was habituated to RT to accelerate because of TSW, but now that you say it, LT makes more sense, because the acc stick is on the left side in germany.

> I dunno It's not perfect yet and feel like there's a lot more work for a proper controller support

Yes absolutely. It's just the basics you need to drive the train after you set it up once.

**Review by HaSa1002 — DISMISSED** [review]
lgtm, but please squash into one

**Review by HaSa1002 — APPROVED** [review]
Why didn't I get a notification here. Anyway lgtm.

**Comment by HaSa1002** [comment]
Thank you very much ❤️

**Pull request merged**
