### PR TITLE
Fix signals and speed limits trying to set themselves to rails, without being in tree

### PR DESCRIPTION
**Pull request by HaSa1002**
fixes the logging issue: https://github.com/Jean28518/Libre-TrainSim/issues/98#issuecomment-928993279

### CODE REVIEW

**Comment by Jean28518** [comment]
We also need WarnSpeeds and Stations for this fix. they should work the same way.

Could you add those two please?

**Comment by HaSa1002** [comment]
done

**Comment by HaSa1002** [comment]
Do @DasCapschen the favor and merge #125 first 😆

**Comment by HaSa1002** [comment]
rebased

**Pull request merged**
