### PR TITLE
Add Brazilian Portuguese translation

### LINKED ISSUE #555: Language Submission Brazilian Portuguese
[ptbr.zip](https://github.com/Libre-TrainSim/Libre-TrainSim/files/14876833/ptbr.zip)

Hello!

I'm submitting the files with the translation for Brazilian Portuguese, please let me know if there's anything that needs to be changed.

### PR DESCRIPTION
**Pull request by Jomosoto**
The Brazilian Portuguese translation by @RafaMGam

Resolves #555

### CODE REVIEW

**Review by HaSa1002 — DISMISSED** [review]
lgtm. Thank you

**Comment by Jomosoto** [comment]
Sorry I forgot to correct the name that @RafaMGam would like to be listed under.

**Review by HaSa1002 — APPROVED** [review]
still looking good an still not a real review ':)

**Comment by Jomosoto** [comment]
Thank you very much for the translation @RafaMGam :heart:

**Pull request merged**
