### PR TITLE
Add render stats to debug window

### PR DESCRIPTION
**Pull request by HaSa1002**
Adds render stats below the debug FPS counter. Can be enabled and disabled using ProjectSettings and an in-game toggle.

I had my reasons...
grafik
grafik

### CODE REVIEW

**Review by DasCapschen — APPROVED** [review]
Looks fine to me. Hope with that we can figure out why it runs so poorly 🙈

**Comment by HaSa1002** [comment]
I am quite impressed it runs at all actually xD I mean 100 million verts a quite a feat

**Comment by DasCapschen** [comment]
Not too many draw calls though... Multimeshes should be the reason for that.
Also a 3080 can do 30 trillion floating point ops a second, 100 million verts should be fine :D

**Comment by HaSa1002** [comment]
I probably have to compare that to a high quality demo scene perhaps. Something with proper PBR mats. I guess the high amount of surface changes contributes? I dunno. Doesn't really look fishy apart the vert count

**Comment by DasCapschen** [comment]
Many changes of things per frame, that seems weird to me, tbh

**Comment by HaSa1002** [comment]
yeah and 1,2k mats is quite a bit. Especially considering we only have like 15 materials and this is an editor running

**Comment by DasCapschen** [comment]
Perhaps we're duplicating multimesh materials somewhere? Or do some materials have "local to scene" checked or something?   
We don't even have that many materials in the project! 😅

**Pull request merged**
