### PR TITLE
Fix Tutorials

### LINKED ISSUE #270: Signal Tutorials and German Safety Tutorials broke with new chunk system
Tutorials use relative paths, but stuff was moved around, so they broke. 
Should be an easy fix :)

### PR DESCRIPTION
**Pull request by DasCapschen**
- [x] fix PZB tutorial
- [x] fix Sifa tutorial
- [x] fix KS Signal tutorial
- [x] fix HL Signal tutorial
- [x] fix HV Form Signal tutorial
- [x] fix HV Light Signal tutorial

fixes #270

### CODE REVIEW

**Comment by HaSa1002** [comment]
I fixed HL Signals and updated all the tutorials. I hope, I got them right.

**Review by HaSa1002 — APPROVED** [review]
your changes are looking good

**Comment by DasCapschen** [comment]
Thanks for your work Hasa!
Signal tutorials now all work as intended! 🥳

**Comment by DasCapschen** [comment]
You can merge this if you are happy with it. I am happy with it.

**Pull request merged**
