### PR TITLE
Add new logo

### PR DESCRIPTION
**Pull request by HaSa1002**
Adds a new logo, banner variants, and updates the description.

<details>
<summary>Logos</summary>

lts_logo_16
lts_logo_32
lts_logo_64
lts_logo_128
lts_logo_256
lts_logo_512

</details>

<details>
<summary>Banners</summary>

lts_banner_name
lts_banner_version
lts_banner_both

</details>

### CODE REVIEW

**Comment by DasCapschen** [comment]
I guess it's an SVG, so it may just be my browser rendering it wrong, but... why isn't the red in front on the larger logo?
grafik

Other than that, the only thing I would change about the logo is to make sure the red completely covers the blue, right now, there is still some blue visible around the red. (see the smaller version in the screenshot^, there's blue below it and on the lower part of the S)

About the banners... yeah I guess they are fine. I guess for a banner the aspect ratio is a bit weird, like shouldn't a banner be wider than it's tall? :thinking:
And of course the logo suggestions also apply.

**Comment by HaSa1002** [comment]
I didn't know which version I like more. I did that on purpose actually :D

The banners are wider than they are tall...

**Comment by Miksimus1** [comment]
Hi everybody,
I hope it's not too late...

I'm an illustrator, and because I like so much LibreTrain Sim, I made a logo.
I don't know if it could be ok for you, but i send it anyway. I try to respect the logo above.
proposition_logo01

Thanks for this project !

**Comment by DasCapschen** [comment]
Thank you for your illustration!
I like the way it looks 3D, but I think it has too much detail to be used as a logo. (since a logo would also need to be used in very small sizes)
But maybe it can be used as a banner or something similar on the webite 🤔 
I wonder what @HaSa1002 and @Jean28518 think about it.

**Comment by HaSa1002** [comment]
@Miksimus1 I very much like it. Can you make a *quick* sketch for smaller resolutions, please? Feel free to go into a completely different direction, too. Nothing is set in stone atm.
In the end we need at least the following sizes for the icon:
 * 16x16px
 * 32x32px
 * 64x64px
 * 128x128px
 * 256x256px
 * 512x512px

I have no problem with a scaled down version of the logo but you may wanna reduce details.

Additionally I would like to have some banners with and without names and the version (see my banners example). I wanna use them for version branding where applicable. (I can edit them myself, but maybe you have some thoughts how it could be nicely arranged). Feel free to join on [Discord](https://discord.com/invite/AQdAtZZ) to quicken the communication a little bit.

**Comment by Miksimus1** [comment]
Okay, I’ll see what I can do :-)

@DasCapschen , @HaSa1002 ,
Thanks for your feedback.

For Discord, I can't use it. But i'll see regularly here. Thanks :)

**Comment by Miksimus1** [comment]
OK, I quickly modify my drawing for the different sizes : 
proposition_logo01_16x16
proposition_logo01_32x32
proposition_logo01_64x64
proposition_logo01_128x128
proposition_logo01_256x256
proposition_logo01_512x512

I'm thinking about other propositions...

**Comment by Miksimus1** [comment]
And as banners...
 don't know if you want to keep the original font.... so I'll change it if necessary... ;-)
proposition_logo01_512x512_with_text
proposition_logo01_512x512_with_text_alt01

I add text with Inkscape... So if you want to change any text, you can use it with my source file : 
proposition_logo01_512x512



Be sure you have these fonts :
- Revert Round BRK
- Waree

**Comment by HaSa1002** [comment]
Thanks. The smaller variants are looking good.
Regarding the banners, I like them except for the main font (The monospace font is fine). It is too playful IMO.

**Comment by Miksimus1** [comment]
OK, so here is another try with the same font for all the text (Waree) : 

proposition_logo01_512x512_with_text_alt02

**Comment by Jean28518** [comment]
I like the new logo!
But I don't know how it looks in small...

But for me that would be okay

**Comment by HaSa1002** [comment]
So I updated the logos and banners. I should have mentioned the banner size being 512x350 or 512x290 respectively.
Here are the banners (I chose Bahnschrift because I cannot install Waree). Ideally we should aim for a general redesign of our UI and branding. All of the changes are mostly band-aiding. I'd like to include you @Miksimus1 in discussions for a unified UI/UX for 1.0. I learned a lot about UI/UX in past months but I lack some visual sensitivity. So basically, I know what we should do but I am not the best to decide on visual stuff.

lts_banner_both
lts_banner_name
lts_banner_version

Anyway, this PR should be good to go 🥳

**Review by DasCapschen — APPROVED** [review]
lgtm

**Comment by DasCapschen** [comment]
So it is decided. New Logo, here we come. Choo Choo 🚂

**Comment by HaSa1002** [comment]
Party!!! 🎉 Thanks @Miksimus1 for your work.

**Comment by Miksimus1** [comment]
Yeah ! You're welcome !
I'm happy to contribute.
Ok for help on UI / UX. I hope I have skills to doing it ;-)

**Comment by HaSa1002** [comment]
I am going to ping you when work starts :P

**Comment by Miksimus1** [comment]
OK Thanks !

**Comment by Miksimus1** [comment]
So, here is Waree font, if you want to use it. (Bahnschrift is made by Microsoft and i don't know if it's open...)
[Waree.zip](https://github.com/Libre-TrainSim/Libre-TrainSim/files/8056996/Waree.zip)

**Comment by Miksimus1** [comment]
Also, i made logos with white letters "LTS". I could be usefull....
<p style="background-color:#777;">

proposition_logo01 1_white-LTS_128x128
proposition_logo01 1_white-LTS_256x256
proposition_logo01 1_white-LTS_512x512

And with a background...
proposition_logo01 1_white-LTS_background_b1_512x512
proposition_logo01 1_white-LTS_background_b2_512x512

</p>

**Comment by DasCapschen** [comment]
Ooh, i *really* like the last one :eyes:

**Comment by HaSa1002** [comment]
Yes they are nice. We should put all of them into a lts-design repo.

**Pull request merged**
