### PR TITLE
Fix Gizmo selection and implement mouse position restoring

### LINKED ISSUE #416: Gizmo: Cursor doesn't show up where it was captured.
### Summary
When modifying an objects position or rotation the cursor gets captured. Once the change is done, the cursor is reset to some position but not the original one.

### How to reproduce
1. Open any map in the editor.
2. Select an object or a rail.
3. Ensure the gizmo is visible and enabling manual moving if necessary.
4. **Move or rotate the object.**

### Observed behavior
The cursor is captured and released on different positions.

### Expected behavior
The cursor is captured (or not captured at all) and released at the original position.

### Version
 - Game Version: 0.9.beta1
 - OS: Windows

### PR DESCRIPTION
**Pull request by nalquas**
Some improvements/fixes for the Gizmo:

- Fixes the collision shapes and axis positioning in `Gizmo.tscn`.
- Fixes the Gizmo's `x_active` (etc.) logic, as it was *very* broken before, especially when dragging outside of the axis collision shapes. We now store corresponding `x_hovered` (etc.) states and use these to determine active states. Look at the code for more details, but basically I did some refactoring.
- Save and restore the mouse position before and after mouse capture (Fixes #416).

### CODE REVIEW

**Review by HaSa1002 — DISMISSED** [review]
Changes improve the gizmo. They don't follow our GDScript guide (they aren't typed), but I don't really care as it has to be redone anyway. The axis are inverted if you look at the gizmo from the wrong side.

**Comment by HaSa1002** [comment]
I just messed up the history a little bit while trying to fix a space issue. Feel free to rebase or give me a go when you wanna have this PR merged.

**Review by HaSa1002 — DISMISSED** [review]

**Comment by nalquas** [comment]
> They don't follow our GDScript guide (they aren't typed)

I added static typing to the code now.

>The axis are inverted if you look at the gizmo from the wrong side.

That was already an issue before. The movement logic of the gizmo obviously needs a complete rewrite.

> Feel free to rebase or give me a go when you wanna have this PR merged.

Yup, merge away.

**Review by HaSa1002 — APPROVED** [review]
lgtm

**Comment by HaSa1002** [comment]
Thanks ❤️

**Pull request merged**
